import {auth,db} from './firebase.js';
import {onAuthStateChanged,signOut} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import {ref,onValue,push,set,update} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js';

const app=document.getElementById('app');
onAuthStateChanged(auth,user=>{if(!user){location.href='login.html';return} renderShell(user);loadDashboard(user)});

function renderShell(user){app.innerHTML=`<div class="layout"><aside class="sidebar" id="sidebar"><div class="brand">Project Afri-Health<small>Private Team Hub</small></div><nav class="nav"><a href="#dashboard" class="active">Dashboard</a><a href="#tasks">Tasks & Deliverables</a><a href="#meetings">Meetings</a><a href="#documents">Documents</a><a href="#team">Team</a><a href="#departments">Departments</a><a href="#announcements">Announcements</a><a href="#activity">Activity</a></nav></aside><main class="main"><div class="topbar"><div><button class="btn secondary mobile-menu" id="menu">☰</button><h1 id="pageTitle">Dashboard</h1><div class="muted">Keep the team aligned, informed and moving.</div></div><div class="userbar"><div class="avatar">${(user.email||'A')[0].toUpperCase()}</div><span class="user-name">${user.email||'Team member'}</span><button class="btn danger" id="logout">Logout</button></div></div><div id="page"></div></main></div><div class="modal" id="modal"></div>`;
document.getElementById('logout').onclick=()=>signOut(auth);document.getElementById('menu').onclick=()=>document.getElementById('sidebar').classList.toggle('open');window.addEventListener('hashchange',()=>route(user));route(user)}
function route(user){const h=location.hash.replace('#','')||'dashboard';document.querySelectorAll('.nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+h));document.getElementById('pageTitle').textContent=({dashboard:'Dashboard',tasks:'Tasks & Deliverables',meetings:'Meetings',documents:'Documents',team:'Team',departments:'Departments',announcements:'Announcements',activity:'Activity'})[h]||'Dashboard'; if(h==='dashboard')loadDashboard(user);else if(h==='tasks')loadTasks();else if(h==='meetings')loadMeetings();else if(h==='team')loadTeam();else if(h==='departments')loadDepartments();else if(h==='announcements')loadAnnouncements();else if(h==='activity')loadActivity();else if(h==='documents')loadDocuments()}
function listen(path,cb){onValue(ref(db,path),snap=>cb(snap.val()||{}))}
function esc(x=''){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function loadDashboard(){listen('tasks',tasks=>listen('meetings',meetings=>listen('announcements',anns=>{const ts=Object.values(tasks),ms=Object.values(meetings),as=Object.values(anns);document.getElementById('page').innerHTML=`<div class="grid"><div class="card stat"><span class="muted">Open tasks</span><strong>${ts.filter(x=>x.status!=='Completed').length}</strong></div><div class="card stat"><span class="muted">Completed</span><strong>${ts.filter(x=>x.status==='Completed').length}</strong></div><div class="card stat"><span class="muted">Meetings</span><strong>${ms.length}</strong></div><div class="card stat"><span class="muted">Announcements</span><strong>${as.length}</strong></div></div><div class="grid-2 section"><div class="card"><div class="section-title"><h2>Next meeting</h2><a class="btn secondary" href="#meetings">View all</a></div>${ms.length?`<div class="item"><b>${esc(ms[ms.length-1].title)}</b><p class="muted">${esc(ms[ms.length-1].date||'')}</p><p>${esc(ms[ms.length-1].agenda||'No agenda yet.')}</p></div>`:'<div class="empty">No meetings added yet.</div>'}</div><div class="card"><div class="section-title"><h2>Recent announcements</h2><a class="btn secondary" href="#announcements">View all</a></div>${as.slice(-3).reverse().map(a=>`<div class="item"><b>${esc(a.title)}</b><p>${esc(a.message)}</p></div>`).join('')||'<div class="empty">No announcements yet.</div>'}</div></div><div class="card section"><div class="section-title"><h2>Current team priority</h2><span class="badge">Team focus</span></div><p>Use Tasks & Deliverables to assign the next concrete actions for each department. Keep WhatsApp/Teams for conversation, and keep final tasks, deadlines and decisions here.</p></div>`})))}
function loadTasks(){listen('tasks',data=>{const items=Object.entries(data);document.getElementById('page').innerHTML=`<div class="section-title"><h2>Team tasks</h2><button class="btn primary" onclick="window.openTask()">+ Add task</button></div><div class="list">${items.map(([id,t])=>`<div class="item"><div class="item-head"><div><b>${esc(t.title)}</b><div class="muted">${esc(t.department||'')} · ${esc(t.owner||'Unassigned')}</div></div><span class="badge ${t.status==='Blocked'?'danger':t.status==='In Progress'?'warn':''}">${esc(t.status||'Not Started')}</span></div><p>${esc(t.description||'')}</p><small>Due: ${esc(t.deadline||'No deadline')}</small></div>`).join('')||'<div class="card empty">No tasks yet. Add the first deliverable.</div>'}</div>`})}
window.openTask=()=>{const m=document.getElementById('modal');m.className='modal show';m.innerHTML=`<div class="modal-card"><div class="modal-head"><h2>Add task</h2><button class="close" onclick="window.closeModal()">×</button></div><form id="taskForm"><label>Task title<input id="tTitle" required></label><label>Department<select id="tDept"><option>AI & Edge Technology</option><option>Health & Research</option><option>Product & UX</option><option>Business, Presentation & Partnerships</option></select></label><label>Owner<input id="tOwner"></label><label>Deadline<input id="tDeadline" type="date"></label><label>Description<textarea id="tDesc"></textarea></label><button class="btn primary">Save task</button></form></div>`;document.getElementById('taskForm').onsubmit=async e=>{e.preventDefault();await push(ref(db,'tasks'),{title:tTitle.value,department:tDept.value,owner:tOwner.value,deadline:tDeadline.value,description:tDesc.value,status:'Not Started',createdAt:Date.now()});window.closeModal()}}
window.closeModal=()=>{document.getElementById('modal').className='modal'};
function loadMeetings(){listen('meetings',data=>{document.getElementById('page').innerHTML=`<div class="section-title"><h2>Meetings</h2><button class="btn primary" onclick="window.openMeeting()">+ Add meeting</button></div><div class="list">${Object.values(data).map(m=>`<div class="item"><div class="item-head"><b>${esc(m.title)}</b><span class="badge">${esc(m.date||'')}</span></div><p>${esc(m.agenda||'')}</p>${m.link?`<a class="btn secondary" href="${esc(m.link)}" target="_blank">Meeting link</a>`:''}</div>`).join('')||'<div class="card empty">No meetings scheduled.</div>'}</div>`})}
window.openMeeting=()=>{const m=document.getElementById('modal');m.className='modal show';m.innerHTML=`<div class="modal-card"><div class="modal-head"><h2>Add meeting</h2><button class="close" onclick="window.closeModal()">×</button></div><form id="meetingForm"><label>Title<input id="mTitle" required></label><label>Date & time<input id="mDate" type="datetime-local" required></label><label>Meeting link<input id="mLink" placeholder="Microsoft Teams / Google Meet / Zoom"></label><label>Agenda<textarea id="mAgenda"></textarea></label><label>Preparation required<textarea id="mPrep" placeholder="What should members bring or prepare?"></textarea></label><button class="btn primary">Save meeting</button></form></div>`;document.getElementById('meetingForm').onsubmit=async e=>{e.preventDefault();await push(ref(db,'meetings'),{title:mTitle.value,date:mDate.value,link:mLink.value,agenda:mAgenda.value,preparation:mPrep.value,createdAt:Date.now()});window.closeModal()}}
function loadTeam(){listen('members',data=>{document.getElementById('page').innerHTML=`<div class="section-title"><h2>Team directory</h2><button class="btn primary" onclick="window.openMember()">+ Add member</button></div><div class="grid">${Object.values(data).map(m=>`<div class="card"><div class="avatar">${esc((m.name||'?')[0])}</div><h3>${esc(m.name)}</h3><span class="badge">${esc(m.department||'')}</span><p class="muted">${esc(m.role||'')}</p><p>${esc(m.skills||'')}</p></div>`).join('')||'<div class="card empty">No team members added.</div>'}</div>`})}
window.openMember=()=>{const m=document.getElementById('modal');m.className='modal show';m.innerHTML=`<div class="modal-card"><div class="modal-head"><h2>Add member</h2><button class="close" onclick="window.closeModal()">×</button></div><form id="memberForm"><label>Name<input id="pName" required></label><label>Department<select id="pDept"><option>AI & Edge Technology</option><option>Health & Research</option><option>Product & UX</option><option>Business, Presentation & Partnerships</option></select></label><label>Role<input id="pRole"></label><label>Skills<input id="pSkills"></label><button class="btn primary">Save member</button></form></div>`;document.getElementById('memberForm').onsubmit=async e=>{e.preventDefault();await push(ref(db,'members'),{name:pName.value,department:pDept.value,role:pRole.value,skills:pSkills.value});window.closeModal()}}
function loadDepartments(){document.getElementById('page').innerHTML=`<div class="grid">${[['AI & Edge Technology','AI model, Edge AI, datasets, evaluation, technical integration.'],['Health & Research','Health problem research, evidence, users, safety, ethics and research.'],['Product & UX','Features, user journey, wireframes, usability, prototype and feedback.'],['Business, Presentation & Partnerships','Business model, partners, stakeholders, pitch, funding and roadmap.']].map(d=>`<div class="card"><span class="badge">Department</span><h2>${d[0]}</h2><p>${d[1]}</p></div>`).join('')}</div>`}
function loadAnnouncements(){listen('announcements',data=>{document.getElementById('page').innerHTML=`<div class="section-title"><h2>Announcements</h2><button class="btn primary" onclick="window.openAnnouncement()">+ New announcement</button></div><div class="list">${Object.values(data).reverse().map(a=>`<div class="item"><div class="item-head"><b>${esc(a.title)}</b><small>${new Date(a.createdAt||Date.now()).toLocaleString()}</small></div><p>${esc(a.message)}</p></div>`).join('')||'<div class="card empty">No announcements.</div>'}</div>`})}
window.openAnnouncement=()=>{const m=document.getElementById('modal');m.className='modal show';m.innerHTML=`<div class="modal-card"><div class="modal-head"><h2>New announcement</h2><button class="close" onclick="window.closeModal()">×</button></div><form id="annForm"><label>Title<input id="aTitle" required></label><label>Message<textarea id="aMsg" required></textarea></label><button class="btn primary">Publish</button></form></div>`;document.getElementById('annForm').onsubmit=async e=>{e.preventDefault();await push(ref(db,'announcements'),{title:aTitle.value,message:aMsg.value,createdAt:Date.now()});window.closeModal()}}
function loadActivity(){listen('activity',data=>{document.getElementById('page').innerHTML=`<div class="card"><h2>Activity</h2><div class="list">${Object.values(data).reverse().map(x=>`<div class="item"><b>${esc(x.text)}</b><small class="muted">${new Date(x.createdAt||Date.now()).toLocaleString()}</small></div>`).join('')||'<div class="empty">Activity will appear here as the hub grows.</div>'}</div></div>`})}
function loadDocuments(){document.getElementById('page').innerHTML=`<div class="card"><h2>Documents</h2><p class="muted">Firebase Storage upload and document metadata are prepared for the next build step.</p><div class="item"><b>Recommended folders</b><p>Research · AI & Edge · Product & UX · Business · Meetings · Governance · Presentations</p></div></div>`}
