import { auth, db, isDemoMode } from './firebase.js';
import { onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import { ref, onValue, push } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js';

const app=document.getElementById('app');
const demoSeed={
 tasks:{
  t1:{title:'Define project workspace requirements',department:'Health & Research',owner:'Faith-Tabitha Olanipekun',deadline:'2026-09-29',description:'Compile the team requirements for the official Afri-Health Team Hub.',status:'In Progress'},
  t2:{title:'Create initial product user flow',department:'Product & UX',owner:'Netochukwu Ihuoma Chimezie',deadline:'2026-09-30',description:'Map how members will move through the Team Hub.',status:'Not Started'},
  t3:{title:'Document technical architecture',department:'AI & Edge Technology',owner:'Wisdom Ifeanyichukwu Ohagba',deadline:'2026-10-01',description:'Define the technical structure and future integration approach.',status:'Not Started'},
  t4:{title:'Draft sustainability and partnership notes',department:'Business, Presentation & Partnerships',owner:'Tadisashe Nhoro',deadline:'2026-10-02',description:'Document potential sustainability, partnership and presentation needs.',status:'Not Started'}
 },
 meetings:{m1:{title:'Project Afri-Health Team Meeting',date:'2026-09-27T20:00',agenda:'Review team structure, requirements and next deliverables.',preparation:'Each department should bring its current responsibilities and proposed deliverables.'}},
 announcements:{a1:{title:'Welcome to the Team Hub',message:'This is the central workspace for Project Afri-Health. Keep final tasks, deadlines, documents and decisions here.',createdAt:Date.now()}},
 members:{
  p1:{name:'Faith-Tabitha Olanipekun',department:'Health & Research',role:'Health & Research',skills:'Health research, user research, evidence, safety and ethics'},
  p2:{name:'Tadisashe Nhoro',department:'Business, Presentation & Partnerships',role:'Business & Partnerships',skills:'Business model, partnerships, presentation and sustainability'},
  p3:{name:'Netochukwu Ihuoma Chimezie',department:'Product & UX',role:'Product & UX',skills:'Product design, user journey, wireframes and usability'},
  p4:{name:'Wisdom Ifeanyichukwu Ohagba',department:'AI & Edge Technology',role:'AI & Edge Technology',skills:'AI models, Edge AI, datasets and technical integration'}
 },
 activity:{x1:{text:'Project Afri-Health Team Hub preview initialized.',createdAt:Date.now()}}
};

function getDemoData(path){
 const saved=JSON.parse(localStorage.getItem('afri_demo_data')||'null')||demoSeed;
 return saved[path]||{};
}
function saveDemoData(path,data){const all=JSON.parse(localStorage.getItem('afri_demo_data')||'null')||structuredClone(demoSeed);all[path]=data;localStorage.setItem('afri_demo_data',JSON.stringify(all));}
function listen(path,cb){
 if(isDemoMode){cb(getDemoData(path));return ()=>{};}
 onValue(ref(db,path),snap=>cb(snap.val()||{}));
}
async function add(path,value){
 if(isDemoMode){const d=getDemoData(path);d['demo_'+Date.now()]=value;saveDemoData(path,d);return;}
 await push(ref(db,path),value);
}
function esc(x=''){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}

function start(user){renderShell(user);loadDashboard();}
if(isDemoMode){
 const email=localStorage.getItem('afri_demo_user');
 if(!email){location.href='login.html';}else start({email});
}else{
 onAuthStateChanged(auth,user=>{if(!user){location.href='login.html';return}start(user);});
}

function renderShell(user){
 app.innerHTML=`<div class="layout"><aside class="sidebar" id="sidebar"><div class="brand">Project Afri-Health<small>Official Team Hub</small></div><nav class="nav"><a href="#dashboard" class="active">Dashboard</a><a href="#tasks">Tasks & Deliverables</a><a href="#meetings">Meetings</a><a href="#documents">Documents</a><a href="#team">Team</a><a href="#departments">Departments</a><a href="#announcements">Announcements</a><a href="#activity">Activity</a></nav></aside><main class="main"><div class="topbar"><div><button class="btn secondary mobile-menu" id="menu">☰</button><h1 id="pageTitle">Dashboard</h1><div class="muted">Keep the team aligned, informed and moving.</div></div><div class="userbar"><div class="avatar">${(user.email||'A')[0].toUpperCase()}</div><span class="user-name">${esc(user.email||'Team member')}</span><button class="btn danger" id="logout">Logout</button></div></div><div id="page"></div></main></div><div class="modal" id="modal"></div>`;
 document.getElementById('logout').onclick=()=>{if(isDemoMode){localStorage.removeItem('afri_demo_user');location.href='login.html'}else signOut(auth)};
 document.getElementById('menu').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
 window.addEventListener('hashchange',()=>route());route();
}
function route(){const h=location.hash.replace('#','')||'dashboard';document.querySelectorAll('.nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+h));document.getElementById('pageTitle').textContent=({dashboard:'Dashboard',tasks:'Tasks & Deliverables',meetings:'Meetings',documents:'Documents',team:'Team',departments:'Departments',announcements:'Announcements',activity:'Activity'})[h]||'Dashboard';({dashboard:loadDashboard,tasks:loadTasks,meetings:loadMeetings,documents:loadDocuments,team:loadTeam,departments:loadDepartments,announcements:loadAnnouncements,activity:loadActivity}[h]||loadDashboard)();}
function loadDashboard(){listen('tasks',tasks=>listen('meetings',meetings=>listen('announcements',anns=>{const ts=Object.values(tasks),ms=Object.values(meetings),as=Object.values(anns);document.getElementById('page').innerHTML=`<div class="demo-banner">${isDemoMode?'Preview mode — connect Firebase later to make this a live private team system.':''}</div><div class="grid"><div class="card stat"><span class="muted">Open tasks</span><strong>${ts.filter(x=>x.status!=='Completed').length}</strong></div><div class="card stat"><span class="muted">Completed</span><strong>${ts.filter(x=>x.status==='Completed').length}</strong></div><div class="card stat"><span class="muted">Meetings</span><strong>${ms.length}</strong></div><div class="card stat"><span class="muted">Announcements</span><strong>${as.length}</strong></div></div><div class="grid-2 section"><div class="card"><div class="section-title"><h2>Next meeting</h2><a class="btn secondary" href="#meetings">View all</a></div>${ms.length?`<div class="item"><b>${esc(ms[Object.keys(ms)[Object.keys(ms).length-1]].title)}</b><p class="muted">${esc(ms[Object.keys(ms)[Object.keys(ms).length-1]].date||'')}</p><p>${esc(ms[Object.keys(ms)[Object.keys(ms).length-1]].agenda||'No agenda yet.')}</p></div>`:'<div class="empty">No meetings added yet.</div>'}</div><div class="card"><div class="section-title"><h2>Recent announcements</h2><a class="btn secondary" href="#announcements">View all</a></div>${as.slice(-3).reverse().map(a=>`<div class="item"><b>${esc(a.title)}</b><p>${esc(a.message)}</p></div>`).join('')||'<div class="empty">No announcements yet.</div>'}</div></div><div class="card section"><div class="section-title"><h2>Current team priority</h2><span class="badge">Team focus</span></div><p>Keep final tasks, deadlines, documents and decisions in the Team Hub while WhatsApp/Teams remain available for conversation.</p></div>`}))) }
function loadTasks(){listen('tasks',data=>{const items=Object.entries(data);document.getElementById('page').innerHTML=`<div class="section-title"><h2>Team tasks</h2><button class="btn primary" onclick="window.openTask()">+ Add task</button></div><div class="list">${items.map(([id,t])=>`<div class="item"><div class="item-head"><div><b>${esc(t.title)}</b><div class="muted">${esc(t.department||'')} · ${esc(t.owner||'Unassigned')}</div></div><span class="badge">${esc(t.status||'Not Started')}</span></div><p>${esc(t.description||'')}</p><small>Due: ${esc(t.deadline||'No deadline')}</small></div>`).join('')||'<div class="card empty">No tasks yet.</div>'}</div>`})}
window.openTask=()=>modal(`<h2>Add task</h2><form id="taskForm"><label>Task title<input id="tTitle" required></label><label>Department<select id="tDept"><option>AI & Edge Technology</option><option>Health & Research</option><option>Product & UX</option><option>Business, Presentation & Partnerships</option></select></label><label>Owner<input id="tOwner"></label><label>Deadline<input id="tDeadline" type="date"></label><label>Description<textarea id="tDesc"></textarea></label><button class="btn primary">Save task</button></form>`,async e=>{await add('tasks',{title:tTitle.value,department:tDept.value,owner:tOwner.value,deadline:tDeadline.value,description:tDesc.value,status:'Not Started',createdAt:Date.now()});closeModal();route()});
function loadMeetings(){listen('meetings',data=>{document.getElementById('page').innerHTML=`<div class="section-title"><h2>Meetings</h2><button class="btn primary" onclick="window.openMeeting()">+ Add meeting</button></div><div class="list">${Object.values(data).map(m=>`<div class="item"><div class="item-head"><b>${esc(m.title)}</b><span class="badge">${esc(m.date||'')}</span></div><p>${esc(m.agenda||'')}</p><p class="muted">Preparation: ${esc(m.preparation||'')}</p>${m.link?`<a class="btn secondary" href="${esc(m.link)}" target="_blank">Meeting link</a>`:''}</div>`).join('')||'<div class="card empty">No meetings scheduled.</div>'}</div>`})}
window.openMeeting=()=>modal(`<h2>Add meeting</h2><form id="meetingForm"><label>Title<input id="mTitle" required></label><label>Date & time<input id="mDate" type="datetime-local" required></label><label>Meeting link<input id="mLink" placeholder="Microsoft Teams / Google Meet / Zoom"></label><label>Agenda<textarea id="mAgenda"></textarea></label><label>Preparation required<textarea id="mPrep"></textarea></label><button class="btn primary">Save meeting</button></form>`,async e=>{await add('meetings',{title:mTitle.value,date:mDate.value,link:mLink.value,agenda:mAgenda.value,preparation:mPrep.value,createdAt:Date.now()});closeModal();route()});
function loadTeam(){listen('members',data=>{document.getElementById('page').innerHTML=`<div class="section-title"><h2>Team directory</h2><button class="btn primary" onclick="window.openMember()">+ Add member</button></div><div class="grid">${Object.values(data).map(m=>`<div class="card"><div class="avatar">${esc((m.name||'?')[0])}</div><h3>${esc(m.name)}</h3><span class="badge">${esc(m.department||'')}</span><p class="muted">${esc(m.role||'')}</p><p>${esc(m.skills||'')}</p></div>`).join('')||'<div class="card empty">No team members added.</div>'}</div>`})}
window.openMember=()=>modal(`<h2>Add member</h2><form id="memberForm"><label>Name<input id="pName" required></label><label>Department<select id="pDept"><option>AI & Edge Technology</option><option>Health & Research</option><option>Product & UX</option><option>Business, Presentation & Partnerships</option></select></label><label>Role<input id="pRole"></label><label>Skills<input id="pSkills"></label><button class="btn primary">Save member</button></form>`,async e=>{await add('members',{name:pName.value,department:pDept.value,role:pRole.value,skills:pSkills.value});closeModal();route()});
function loadDepartments(){document.getElementById('page').innerHTML=`<div class="grid">${[['AI & Edge Technology','AI model, Edge AI, datasets, evaluation and technical integration.'],['Health & Research','Health research, evidence, users, safety and ethics.'],['Product & UX','Features, user journey, wireframes, usability and prototype.'],['Business, Presentation & Partnerships','Business model, partners, stakeholders, pitch and sustainability.']].map(d=>`<div class="card"><span class="badge">Department</span><h2>${d[0]}</h2><p>${d[1]}</p></div>`).join('')}</div>`}
function loadAnnouncements(){listen('announcements',data=>{document.getElementById('page').innerHTML=`<div class="section-title"><h2>Announcements</h2><button class="btn primary" onclick="window.openAnnouncement()">+ New announcement</button></div><div class="list">${Object.values(data).reverse().map(a=>`<div class="item"><div class="item-head"><b>${esc(a.title)}</b><small>${new Date(a.createdAt||Date.now()).toLocaleString()}</small></div><p>${esc(a.message)}</p></div>`).join('')||'<div class="card empty">No announcements.</div>'}</div>`})}
window.openAnnouncement=()=>modal(`<h2>New announcement</h2><form id="annForm"><label>Title<input id="aTitle" required></label><label>Message<textarea id="aMsg" required></textarea></label><button class="btn primary">Publish</button></form>`,async e=>{await add('announcements',{title:aTitle.value,message:aMsg.value,createdAt:Date.now()});closeModal();route()});
function loadActivity(){listen('activity',data=>{document.getElementById('page').innerHTML=`<div class="card"><h2>Activity</h2><div class="list">${Object.values(data).reverse().map(x=>`<div class="item"><b>${esc(x.text)}</b><small class="muted">${new Date(x.createdAt||Date.now()).toLocaleString()}</small></div>`).join('')||'<div class="empty">No activity yet.</div>'}</div></div>`})}
function loadDocuments(){document.getElementById('page').innerHTML=`<div class="card"><h2>Documents</h2><p class="muted">Document uploads will connect to Firebase Storage when Firebase is configured.</p><div class="item"><b>Recommended folders</b><p>Research · AI & Edge · Product & UX · Business · Meetings · Governance · Presentations</p></div></div>`}
function modal(content,onSubmit){const m=document.getElementById('modal');m.className='modal show';m.innerHTML=`<div class="modal-card"><div class="modal-head">${content}<button class="close" onclick="window.closeModal()">×</button></div></div>`;const form=m.querySelector('form');if(form)form.onsubmit=async e=>{e.preventDefault();await onSubmit(e)};}
window.closeModal=()=>document.getElementById('modal').className='modal';
